services:
  - type: web
    name: blog-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js  # or node server.js depending on your entry file
    envVars:
      - key: MONGODB_URI
        value: your-mongodb-uri-here
      - key: JWT_SECRET
        value: your-secret-key-here
